DROP TABLE IF EXISTS hash;
DROP TABLE IF EXISTS ledger;

CREATE TABLE hash (
	id SERIAL PRIMARY KEY,
	value VARCHAR(32) NOT NULL
);

CREATE TABLE ledger (
	id SERIAL PRIMARY KEY,
	amount INT NOT NULL,
	date_created TIMESTAMP DEFAULT now(),
	sender INT NOT NULL,
	receiver INT NOT NULL
);

ALTER TABLE ledger ADD CONSTRAINT fk_sender
FOREIGN KEY (sender) REFERENCES employee ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ledger ADD CONSTRAINT fk_receiver
FOREIGN KEY (receiver) REFERENCES employee ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ledger ADD CONSTRAINT ch_positive
CHECK(amount > 0);

